POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9tZzJAdGVzdC5jb20iLCJleHAiOjE3MDY4OTYwMDcsInVzZXJJZCI6IjIifQ.KX_zmfYFbto3c8zWTsoNfjGB6LfdUJOoY8wXWuqsl0o



