DELETE  http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9tZzFAdGVzdC5jb20iLCJleHAiOjE3MDY4OTIzOTksInVzZXJJZCI6IjEifQ.YdBthmxp7iXxcenTTtsxcFNg3T-IwNdKnwh7JOQpSag

